### ISSUE TITLE
Terminal right click behavior.

### ISSUE THREAD

**Issue by q9HugW** [mRemoteNG/mRemoteNG#2479]
I want the mouse right click in Telnet and Serial connection works like MobaXTerm or Notepad++.
## Expected Behavior

For example if I Telnet or use Serial connection to a switch, I want to copy the text and paste to somewhere else with right click. If I want to paste multiple lines I want it to show me what I will be pasting into, if I want to copy selected text I want it shows me some options like doing the same thing in Notepad.
## Current Behavior

It does copy and paste automatically without any notification when I right click on the terminal. 
## Possible Solution

I don't know if we have any configure needed?
## Your Environment

* Version used: **1.76.20.24645**
* Operating System and version (e.g. Windows 10 1709 x64): Windows 11

**Comment by simonai1254** [comment]
mRemoteNG is using Putty in be background, it's not a behavior mRemoteNG can directly influence. Please see the documentation for putty (https://www.chiark.greenend.org.uk/~sgtatham/putty/docs.html) on how to change such settings. Refer to the mRemoteNG manual here (https://mremoteng.readthedocs.io/en/latest/user_interface/options.html#advanced) on how to get to the Putty-Settings within mRemoteNG

**Comment by q9HugW** [comment]
> 

Thank you, is there any way to change to any other tools? Such as MobaXTerm or Minicom?

**Comment by q9HugW** [comment]
> mRemoteNG is using Putty in be background, it's not a behavior mRemoteNG can directly influence. Please see the documentation for putty (https://www.chiark.greenend.org.uk/~sgtatham/putty/docs.html) on how to change such settings. Refer to the mRemoteNG manual here (https://mremoteng.readthedocs.io/en/latest/user_interface/options.html#advanced) on how to get to the Putty-Settings within mRemoteNG

Thank you, is there any way to change to any other tools? Such as MobaXTerm or Minicom?

**Comment by simonai1254** [comment]
MobaXTerm is a competitor to mRemoteNG, so there is no supported way to change over. 
I'm not sure how well minicom can be included as external tool. 

What has been done so far is to launch openSSH within Powershell by mRemoteNG, you may have a look at #1262. This workaround is not officially supported by the mRemoteNG team so you're on your own.

**Comment by simonai1254** [comment]
Just realized that you might not be aware of it: Putty automatically copies the highlighted text into the clipboard, there is no need for a right click as one is used from other terminals. The right click in putty pastes the highlighted content into the shell (which can cause the issue of re-pasting the selection if you just selected some displayed content). 

The right-click behavior in putty can be changed, but not the copy-on-selection.

**Comment by q9HugW** [comment]
> The right-click behavior in putty can be changed, but not the copy-on-selection.

Do we support any tool supports copy-on-selection?

**Comment by simonai1254** [comment]
> Do we support any tool supports copy-on-selection?

Not sure what you mean, putty does exactly that. When you select the output, it is automatically copied into the clipboard - no need to do anything. This behavior cannot be changed. 
When someone puts something into the clipboard (e.g. prepared commands in text file) they can be inserted into putty with a right click, exactly as you would do it in a CMD window. Here you can change the behavior of the right-click in putty to open up the regular context menu if necessary.

**Comment by q9HugW** [comment]
> > Do we support any tool supports copy-on-selection?
> 
> Not sure what you mean, putty does exactly that. When you select the output, it is automatically copied into the clipboard - no need to do anything. This behavior cannot be changed. When someone puts something into the clipboard (e.g. prepared commands in text file) they can be inserted into putty with a right click, exactly as you would do it in a CMD window. Here you can change the behavior of the right-click in putty to open up the regular context menu if necessary.

Sorry I meant if any tool other than Putty which supports copy-on-selection if Putty doesn't support that.
But I see there's setting "right brings up menu" in Putty.

**Comment by simonai1254** [comment]
> Sorry I meant if any tool other than Putty which supports copy-on-selection if Putty doesn't support that. But I see there's setting "right brings up menu" in Putty.

The thing most people need to get used to is the behavior of putty to automatically copy the selection with no need to do anything else than selecting the desired text. 
I still do not understand your issue as **putty supports copy-on-selection fully.** The right-click settings only affect the pasting-options. 

And as I said if someone would like to use OpenSSH within Powershell (and therefore it's copy/paste behavior) see #1262 for a community supported workaround.

**Comment by q9HugW** [comment]
> > Sorry I meant if any tool other than Putty which supports copy-on-selection if Putty doesn't support that. But I see there's setting "right brings up menu" in Putty.
> 
> The thing most people need to get used to is the behavior of putty to automatically copy the selection with no need to do anything else than selecting the desired text. I still do not understand your issue as **putty supports copy-on-selection fully.** The right-click settings only affect the pasting-options.

I fixed this one, you just need to change default settings under "Window -> Selection" and you will be able to use "copy-on-selection" in Putty.
It might be fine if you only use remote sessions for SSH or Telnet but it will bring you a lot of pain if you connect to a router or switch by using a serial connection cable without "copy-on-selection".

**Comment by simonai1254** [comment]
> It might be fine if you only use remote sessions for SSH or Telnet but it will bring you a lot of pain if you connect to a router or switch by using a serial connection cable without "copy-on-selection".

I use putty regularly for serial connections also to create complete backups of devices or to deploy a prepared script, never had any issues with the way putty works. That's why I still do not get what your problem is (per default _highlight the text you want to copy from the remote device to copy, right click into the console to paste the prepared script_). But if it works now the way you like it's great.

If you got putty to work the way you'd like please proceed with closing this issue, thanks.

**Comment by q9HugW** [comment]
Thank you, I am closing this issue.
