### ISSUE TITLE
Lost focus on RDP's in SmartSize mode.

### ISSUE THREAD

**Issue by janborup** [mRemoteNG/mRemoteNG#2735]
I'm using "RDP's" in SmartSize mode, and each time i'm hitting [Alt + TAB] or [Win + TAB], and back to mRemote, it has lost fokus on the RDP session, and you had to click with the mouse in the window to get focus

The current version "mRemoteNG 1.78.2 NB 3137" (and many PreRelease versions before), has this focus problem, but is work in the last stable version.

Maybe reference to: https://github.com/mRemoteNG/mRemoteNG/issues/520

Can you help here @Kvarkas

**Comment by Kvarkas** [comment]
yes we know about this issue, will be looking next, once sort main list

**Comment by robertpopa22** [comment]
Triage refresh (P4 version-label debt): this issue is tagged with legacy version labels. Please retest on the latest build (fork v1.79.x or upstream dev), then share reproducible steps and expected vs actual behavior. If still valid, keep open and relabel to current triage scope (for example Need 2 check). If fixed, close with resolution.

Current legacy version labels: 1.78.*

**Comment by janborup** [comment]
> Triage refresh (P4 version-label debt): this issue is tagged with legacy version labels. Please retest on the latest build (fork v1.79.x or upstream dev), then share reproducible steps and expected vs actual behavior. If still valid, keep open and relabel to current triage scope (for example Need 2 check). If fixed, close with resolution.
> 
> Current legacy version labels: 1.78.*

Hi Robert
This issue is still pressent in last tagged (3228) excuteable from October 2025, but this is still labeled 1.78.2

**Comment by robertpopa22** [comment]
Implemented fork-side fix package for this bug:

- upstream PR: PR #3116 on `mRemoteNG/mRemoteNG`
- fix scope:
  - refocus active connection when app re-activates (`WM_ACTIVATEAPP`) unless `DisableRefocus` is enabled
  - resilient active-tab lookup fallback in `frmMain.ActivateConnection()` for cases where `ConnectionWindow.ActiveControl` is transient
- fork CI evidence:
  - CI run 21789349478 on `robertpopa22/mRemoteNG`

If useful I can split out a focused regression test harness for this activation/focus path as a follow-up.

---

> *We sincerely appreciate the mRemoteNG maintainers and the wonderful community that has kept this project alive and thriving for over a decade. Your work powers thousands of IT professionals worldwide, including us. Our fork builds entirely on your foundation — we're preparing a consolidated Pull Request to contribute these improvements back to the official project. Thank you for everything you've built.*
>
> *— robertpopa22, community contributor*

**Comment by robertpopa22** [comment]
**Fix available in community release**

This fix is included in a community build from our fork (`robertpopa22/mRemoteNG`, branch `main`). Available from the fork's Releases page.

Please test and let us know if the issue is fully resolved.

---

> *We sincerely appreciate the mRemoteNG maintainers and the wonderful community that has kept this project alive and thriving for over a decade. Your work powers thousands of IT professionals worldwide, including us. Our fork builds entirely on your foundation — we're preparing a consolidated Pull Request to contribute these improvements back to the official project. Thank you for everything you've built.*
>
> *— robertpopa22, community contributor*

**Comment by janborup** [comment]
This is still an issue in the last PreReleasem mRemoteNG 1.78.2 NB 3702
