### ISSUE TITLE
KeePass auto-type not working in beta versions

### ISSUE THREAD

**Issue by Undedist** [mRemoteNG/mRemoteNG#312]
I'm having issues with KeePass auto-type which I use a lot between different RDP connections. It worked perfectly prior to 1.75 Beta 1 (so for example 1.75 Alpha 3), but stopped in Beta 1.
Auto-type obfuscation is disabled in KeePass. I've tried to enable it, didn't give the expected result, still.
Any idea what could be causing this?
I'm running Windows 10, 1607, 14393.576. KeePass 2.34.
Thanks.

**Comment by banym** [comment]
Hi,
I'm curiouse about this feature. How should it work? Is it using a Keepass Plugin to realize the communication or how do I have to setup the tools to make it work?
Regards.

**Comment by Undedist** [comment]
Thanks for the reply.
I'm not aware of it using a plug-in. There's a very detailed description of this feature on their website:
http://keepass.info/help/base/autotype.html

**Comment by banym** [comment]
That's not what I think is the best solution. If you know how the Chrome or Firefox plugin works, there is a lookup logic to querry the keepass database for example by hostname. It would be nice to have KeePass and MRemoteNG work the same way as KeePass and their browser plugins. 

First the application and keepass setup a secure communication channel once and then the application is allowed to querry the login credentials from the database and passes it to RDP or Putty when needed. 

What do you think?

**Comment by Undedist** [comment]
Yes, i'm familiar with the setup used by browsers and 3rd party password managers.
What i'm curious about is why this feature worked perfectly fine prior to first beta of 1.75?
Other that than, i totally agree with you, it would be "the best way forward".
I'm not sure how much development time would be needed from both applications.
I'll check with KeePass devs if they could jump in here and comment.

**Comment by Undedist** [comment]
I think we have identified the issue now. One of the developers replied to my forum post on Sourceforge regarding this issue, his response is:
I don't have an RDP server for testing, but with SSH2 I'm seeing a window focus bug in mRemoteNG. You can reproduce it even without KeePass: run mRemoteNG and connect to some server, run Windows Explorer and minimize it; now the mRemoteNG window should get focused again, but it doesn't.
... so the issue I'm having seems to be related to window focus, perhaps this could be looked at?
Source: https://sourceforge.net/p/keepass/discussion/329220/thread/84e1d6d9/

**Comment by sparerd** [comment]
When I try to use autotype into an RDP session, KeePass appears to be trying to make a ui element with the text "GlassPanelForm" the active window and sending key strokes to that. This element appears to be part of the new ObjectListView that we now use for drawing the connection tree.

I'll need to do more digging to see why this ui element is getting focus rather than the currently active connection.

**Comment by Undedist** [comment]
Thanks for the pdate, David, and for looking into this, much appreciated.

**Comment by sparerd** [comment]
For how much troubleshooting that took, the fix was comically easy.

We're going to release a 1.75 hotfix in a few days due to a few issues that should be fixed asap. This will be included in that release.

**Comment by sakopov** [comment]
I'm on 1.75.7012.16814 and this still an issue. Also using keepass. Clipboard doesn't work inside remote session.
