### ISSUE TITLE
Importing XML wont work

### ISSUE THREAD

**Issue by theovds** [mRemoteNG/mRemoteNG#394]
When I do an export, I'm unable to import it again. 2 errors may occur:
- "Import failed"
- "Please use file > open to open the file"

I wanted to give my colleague an subset of my connections, but this did not work. We both use 1.75 RC1.

Its pretty easy to reproduce. Hope your able to fix this.
Many thanks!

|||
|--:|---|
|Operating system | Windows 10 x64 |
|mRemoteNG version| 1.75 RC1  |

**Comment by kmscode** [comment]
You can't import mremote connection files. You have to open them with file -> open. Did you attempt that? Did that work?

**Comment by theovds** [comment]
No, that didn't work either.
If I do an export from mRemoteNG, I can not import it again. So you could test it yourself.

**Comment by sparerd** [comment]
Currently, connection files exported from mRemoteNG are not valid to import into mRemoteNG. This is working as designed (it's a legacy thing..). However, there is currently no technical reason for this to be the case. We should be able to take this on as a feature request to allow mremoteng exports to be importable.

**Comment by daftu** [comment]
The problem is that you cannot <import> XML file which was previously <export>'ed. 
Of course it's OK that you cannot import regular settings XML (it should be <open>'ed not <import>'ed).
How to reproduce:
1. Right click on folder in your connection pane and select Export to File...
2. Enter the file name and select Export the currently selected folder, leave file format to mRemoteNG XML, click OK
3. Select another folder (or create new "Test" folder), right click on it and select Import-> Import from file, then select XML saved in step 2.
4. You'll get an error that you cannot import standard connection file and you should use File-> Open... instead

Tested on 1.75 RC1

**Comment by daftu** [comment]
In reply to sparerd:
So what for is this functionality? What for to export XML if you're not able to import it?
I'm pretty sure that it worked in previous releases.
It's preposterous to make an feature request to functionality that existed before but now it's broken.

**Comment by sparerd** [comment]
You are right - exported files were importable in previous versions. It was only the regular (non-exported) mRemoteNG files that were not importable.

Seems there was a small bug where the "export" flag was not set on the exported confcons file. The app checks for this "export" flag to be set and will disallow import if it is not set. Changing the exported xml file and setting `export="true"` should provide a work around.

The "export" flag bug is now fixed in commit `f419bff` and will be available in the next release (1.75, either RC or final). There is also no long any reason to do this check, so the code that checks for the export flag will be removed in the next version.

Sorry if I caused any confusion over this issue.

**Comment by kmscode** [comment]
@sparerd - was this one fixed and included? Can this be closed out?

**Comment by sparerd** [comment]
Yep, this is resolved in the current stable release

**Comment by gelinger777** [comment]
we have the issue on the very latest stable version too.

**Comment by maxisam** [comment]
i am using the latest version and it is still an issue. However, I can open it to get all my connections back

**Comment by TiloGit** [comment]
still an issue on mRemoteNG 1.76.20.24615 
here logs if that helps. 
[import-mRemoteNG.log](https://github.com/mRemoteNG/mRemoteNG/files/13230578/import-mRemoteNG.log)
