### ISSUE TITLE
mRemote always failed the first RDP Connection

### ISSUE THREAD

**Issue by seanyh** [mRemoteNG/mRemoteNG#540]
Seems to mostly happen with 2012 servers. First time I connect, it times out. Works fine the 2nd time.
|--:|---|
|Operating system | Windows 2008 R2 x64 |
|mRemoteNG version| 1.75 aplha 3  |

**Comment by kmscode** [comment]
Sorry I'm mobile and don't remember exactly off the top of my head, but... Tools > connections > increase the RDP timeout.

**Comment by seanyh** [comment]
This just seems to wait longer until it doesn't work. Decreasing it seems to work better

**Comment by JMaier1** [comment]
I tried to connect (from Win7 and I tried it from my home and my office computer, both are Win7) to two different Win10 machines - both Win10 are relatively new installed and all updates are on them - and I cant connect. Then I made as first a connection with Microsofts MSTSC.EXE to both of the Win10-computers I suddenly can connect with mRemote.

One Win10 has F-Secure on it,the other one has no protection - so that cant be the reason, both are in the same network (structure).

There seems to be an issue with the first remote-connection after rebooting (in my case) of Win10 computers

**Comment by DjCezzy** [comment]
I think I have the same issue ore something similar. I have all my connections defined with FQDN hostname. When I connect the first time with mRemote it fails, second time it works fine. When I define a connection with the IP address it works fine the first time.

Can someone confirm if this is the same issue as described above?

Client: Windows 10 Pro 1511
mRemote 1.75.7012.16814

**Comment by michalinplus** [comment]
I can confirm @DjCezzy issue, have the same behavior. What's more changing to IP have immediate effect as well.
Client: Windows 10 1709
mRemote: 1.75.7012 (2017-12-01)

**Comment by farosch** [comment]
@seanyh @JMaier1 @DjCezzy @Baryczka 
Could anyone confirm if this is still the case in v1.76.20?

**Comment by 409industries** [comment]
I found a workaround that seems to take care of the symptoms in my mRemoteNG client v.1.76.20.24615

I have Folders under my connections tree, and on the folders I have different username and domain information for the Active Directory domains that servers I am trying to RDP to need for me to authenticate. However, by using some inheritance, is when i see the delay in logging in and the first try timeout problem. RDP would try to connect, fail, then immediately when i tried again the RDP login would work just fine.

My parent folder had the following settings under Folder > Connection:
- Username: user.name
- Password: ************
- Domain: COMPANY

Each server child object had inheritance turned on for Username, Password, and Domain.
(RDP Connection entry)
Inherit Username: Yes
Inherit Password: Yes
Inherit Domain: Yes

I changed both the parent folder and the server RDP connection entry to the following: 

Folder > Connection:
- Username: COMPANY\user.name
- Password: ************
- Domain:

(RDP Connection entry)
Inherit Username: Yes
Inherit Password: Yes
Inherit Domain: No

Now my RDP connections are working on the first try (and quickly too!) I hope this helps someone else out since I was banging my head against the wall for a long time trying to figure this out. Seems like there should be the functionality built in for mRemoteNG to use the "inherit domain" option properly so that it does not cause this first attempt RDP authentication failure problem.

**Comment by Baryczka** [comment]
@409industries That can be one of the culprit. In my company we fixed this problem setting some DNS for local domain. Problem seems to be some domain dns resolution, where failing. Good catch

**Comment by 409industries** [comment]
> @409industries That can be one of the culprit. In my company we fixed this problem setting some DNS for local domain. Problem seems to be some domain dns resolution, where failing. Good catch

Unfortunately, it has turned out this isn't a sure-fire fix. I am still seeing RDP sessions fail on the first attempt only to go right in on the next. Seems to have helped, but isn't working consistently 100% :-(

**Comment by farosch** [comment]
@409industries Could you please provide the mrng logfile the next time this happens?
See https://mremoteng.readthedocs.io/en/latest/troubleshooting.html

**Comment by farosch** [comment]
Also, please check these two:

- https://social.technet.microsoft.com/Forums/Lync/en-US/7c28f7f3-9135-4dd4-8c74-dee2d465ca93/remote-desktop-connection-always-fails-on-first-attempt?forum=w7itpronetworking
- https://superuser.com/questions/1179793/connection-to-servers-only-works-on-second-attempt

**Comment by limex** [comment]
I don't know why it works ... But I fixed the issue with "use console session" = YES.
Maybe my problem was different: I never got a connection with FQN, but always with IP.

**Comment by 409industries** [comment]
> Also, please check these two:
> 
> * https://social.technet.microsoft.com/Forums/Lync/en-US/7c28f7f3-9135-4dd4-8c74-dee2d465ca93/remote-desktop-connection-always-fails-on-first-attempt?forum=w7itpronetworking
> * https://superuser.com/questions/1179793/connection-to-servers-only-works-on-second-attempt

farosch-

Thank you for the links. After confirming that other engineers were having the same problems without using mRemoteNG (they had saved RDPManager sessions), i looked towards the Windows client being the issue and the "Allow Delegating Saved Credentials with NTLM-only Server Authentication" option seems to have fixed this for us. 

Keep up the good work mRemoteNG!

**Comment by robertpopa22** [comment]
Triage refresh (P4 version-label debt): this issue is tagged with legacy version labels. Please retest on the latest build (fork v1.79.x or upstream dev), then share reproducible steps and expected vs actual behavior. If still valid, keep open and relabel to current triage scope (for example Need 2 check). If fixed, close with resolution.

Current legacy version labels: 1.77.2

**Comment by robertpopa22** [comment]
**Fix available for testing**

A fix for this issue has been implemented in our community fork (`robertpopa22/mRemoteNG`, branch `main`). A beta build including this fix is available from the fork's Releases page.

Please test and report if this resolves your issue.

---

> *We sincerely appreciate the mRemoteNG maintainers and the wonderful community that has kept this project alive and thriving for over a decade. Your work powers thousands of IT professionals worldwide, including us. Our fork builds entirely on your foundation — we're preparing a consolidated Pull Request to contribute these improvements back to the official project. Thank you for everything you've built.*
>
> *— robertpopa22, community contributor*
