### ISSUE TITLE
Allow webssites with SSL Certificats issues

### ISSUE THREAD

**Issue by tobias-weiss** [mRemoteNG/mRemoteNG#580]
|Operating system | Windows 7 x64 |
|mRemoteNG version| 1.75 aplha 3  | 1.75.7005.28220

Many Web Interfaces have SSL certificats which do not meet requirements for browser to consider them as trustworthy. In a browsr however, I can overriede the warnings, but not inside mRemoteNG. I tried both gecko as well IE engines.

**Comment by kmscode** [comment]
This was fixed in #454 

Reference issues #195 & #451 

Will be included in 1.76.

**Comment by Maitwo** [comment]
> This was fixed in [#454](https://github.com/mRemoteNG/mRemoteNG/pull/454)
> 
> Reference issues [#195](https://github.com/mRemoteNG/mRemoteNG/issues/195) & [#451](https://github.com/mRemoteNG/mRemoteNG/pull/451)
> 
> Will be included in 1.76.

Hi kmscode, lock like the issue is still present
https://github.com/mRemoteNG/mRemoteNG/issues/195#issuecomment-2700176563

**Comment by Kvarkas** [comment]
kmscode left a project so all issues I am dealing alone at this moment.
